name: app2
description: A Bluetooth Chat App that enables messaging between devices without internet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Bluetooth functionality
  flutter_blue_plus: ^1.14.1

  # UI & Animations
  flutter_animate: ^4.2.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7

  # Device features
  flutter_tts: ^3.8.3
  vibration: ^1.8.1

  # Icons
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700